import { execSync } from 'node:child_process'
import { api, get, post } from './api-client'
import { uniqueName } from './unique-name'
import { tryDelete } from './cleanup'

type TPodState = 'Running' | 'Pending' | 'Failed' | 'Unknown' | 'Succeeded'

type TSandboxResult = {
  output: string
  error?: string
  success: boolean
  exitCode?: number
}

type TSandboxConnectResult = {
  podName: string
  password: string
  port: number
  sandboxId: string
  command: string
}

type TSandboxSessionResult = {
  sessionId: string
  podName: string
  sandboxId: string
  orgId: string
  userId: string
  connectedAt: string
}

type TSandboxSetup = {
  podName: string
  projectId: string
  sandboxId: string
  sandboxName: string
}

const defaultSandboxConfig = {
  image: 'node:22-slim',
  ports: { '3000': { protocol: 'http' } },
  resources: {
    limits: { cpu: '500m', memory: '512Mi' },
    requests: { cpu: '100m', memory: '256Mi' },
  },
}

/**
 * Poll sandbox pod status until it reaches the desired state or times out.
 * Throws if pod enters Failed state (unless that's the desired state) or timeout exceeded.
 */
export const waitForPodState = async (
  orgId: string,
  sandboxId: string,
  podName: string,
  desiredState: TPodState = 'Running',
  maxWaitMs = 90_000,
  intervalMs = 3_000
): Promise<TPodState> => {
  const start = Date.now()
  let lastState: TPodState = 'Unknown'

  while (Date.now() - start < maxWaitMs) {
    const res = await get<{ data: { podName: string; state: TPodState } }>(
      `/orgs/${orgId}/sandboxes/${sandboxId}/status?podName=${podName}`
    )

    if (res.status !== 200)
      throw new Error(`Status check failed: HTTP ${res.status}`)

    lastState = res.data.data.state
    if (lastState === desiredState) return lastState
    if (lastState === 'Failed' && desiredState !== 'Failed')
      throw new Error(`Pod entered Failed state while waiting for ${desiredState}`)

    await new Promise(r => setTimeout(r, intervalMs))
  }

  throw new Error(
    `Timeout after ${maxWaitMs}ms waiting for pod state '${desiredState}' (last: '${lastState}')`
  )
}

/**
 * Execute a command inside a running sandbox pod.
 * Returns the parsed ApiResponse with TSandboxResult.
 */
export const execInPod = async (
  orgId: string,
  sandboxId: string,
  podName: string,
  command: string,
  args?: string[]
) => {
  return await post<{ data: TSandboxResult }>(
    `/orgs/${orgId}/sandboxes/${sandboxId}/exec`,
    { command, podName, args }
  )
}

/**
 * Read a pod's placeholder token map from its K8s annotations via kubectl.
 * Returns a map of { token: secretId } or empty object if none.
 *
 * Uses kubectl from the test runner (dev machine has kubeconfig access).
 * Pod names are generated by our code using alphanumeric nanoid — no injection risk.
 */
export const getPodPlaceholders = (podName: string): Record<string, string> => {
  try {
    const raw = execSync(
      `kubectl get pod ${podName} -o jsonpath='{.metadata.annotations.tdsk\\.app/placeholders}'`,
      { encoding: 'utf-8', timeout: 10_000 }
    ).trim()

    const cleaned = raw.replace(/^'|'$/g, '')
    if (!cleaned || cleaned === 'null') return {}

    return JSON.parse(cleaned)
  } catch {
    return {}
  }
}

/**
 * Read a pod's subdomain from its K8s annotations via kubectl.
 * Pod names are generated by our code using alphanumeric nanoid — no injection risk.
 */
export const getPodSubdomain = (podName: string): string | null => {
  try {
    const raw = execSync(
      `kubectl get pod ${podName} -o jsonpath='{.metadata.annotations.tdsk\\.app/subdomain}'`,
      { encoding: 'utf-8', timeout: 10_000 }
    ).trim().replace(/^'|'$/g, '')
    return raw || null
  } catch {
    return null
  }
}

/**
 * Call POST /:id/connect — auto-starts pod if needed, returns connection info.
 */
export const connectSandbox = async (orgId: string, sandboxId: string) => {
  return await post<{ data: TSandboxConnectResult }>(
    `/orgs/${orgId}/sandboxes/${sandboxId}/connect`,
    {}
  )
}

/**
 * Call GET /:id/sessions — returns active SSH tunnel sessions.
 */
export const getSessions = async (orgId: string, sandboxId: string) => {
  return await get<{ data: TSandboxSessionResult[] }>(
    `/orgs/${orgId}/sandboxes/${sandboxId}/sessions`
  )
}

/**
 * Full pod lifecycle setup: create project + create sandbox config + start pod + wait for Running.
 * Returns IDs needed for tests and cleanup.
 */
export const setupRunningPod = async (
  orgId: string,
  configOverrides?: Record<string, unknown>
): Promise<TSandboxSetup> => {
  const projRes = await post<{ data: Record<string, any> }>(
    `/orgs/${orgId}/projects`,
    { name: uniqueName('sb-test-project'), orgId }
  )
  if (!projRes.ok) throw new Error(`Failed to create project: HTTP ${projRes.status}`)
  const projectId = projRes.data.data.id

  const sandboxName = uniqueName('test-sandbox')
  const sbRes = await post<{ data: Record<string, any> }>(
    `/orgs/${orgId}/sandboxes`,
    {
      name: sandboxName,
      config: { ...defaultSandboxConfig, ...configOverrides },
      orgId,
      projectId,
    }
  )
  if (!sbRes.ok) throw new Error(`Failed to create sandbox config: HTTP ${sbRes.status}`)
  const sandboxId = sbRes.data.data.id

  let startRes: Awaited<ReturnType<typeof post<{ data: { podName: string } }>>>
  for (let attempt = 0; attempt < 3; attempt++) {
    startRes = await post<{ data: { podName: string } }>(
      `/orgs/${orgId}/sandboxes/${sandboxId}/start`,
      { projectId }
    )
    if (startRes.ok) break
    if (attempt < 2) await new Promise(r => setTimeout(r, 3_000 * (attempt + 1)))
  }
  if (!startRes!.ok) throw new Error(`Failed to start pod: HTTP ${startRes!.status}`)
  const podName = startRes!.data.data.podName

  await waitForPodState(orgId, sandboxId, podName, 'Running', 90_000)

  return { podName, projectId, sandboxId, sandboxName }
}

/**
 * Best-effort cleanup: stop pod + delete sandbox config + delete project.
 * All errors are swallowed — cleanup is best-effort.
 */
export const cleanupSandbox = async (
  orgId: string,
  setup: Partial<TSandboxSetup>
) => {
  if (setup.podName && setup.sandboxId) {
    try {
      await api(`/orgs/${orgId}/sandboxes/${setup.sandboxId}/stop`, {
        method: 'DELETE',
        body: { podName: setup.podName },
      })
    } catch { /* best-effort */ }
  }
  if (setup.sandboxId) await tryDelete(`/orgs/${orgId}/sandboxes/${setup.sandboxId}`)
  if (setup.projectId) await tryDelete(`/orgs/${orgId}/projects/${setup.projectId}`)
}
