import { EInviteStatus, Invitation } from '@tdsk/domain'
import { Ids, OrgIds, UserIds, InvitationIds } from '@TDB/seeds/ids.seed'

export const invitationsSeeds: Invitation[] = [
  new Invitation({
    userId: undefined,
    orgId: OrgIds.acme,
    roleType: `member`,
    revokedAt: undefined,
    revokedBy: undefined,
    acceptedAt: undefined,
    invitedBy: Ids.super.user,
    id: InvitationIds.pending,
    email: `newuser@example.com`,
    status: EInviteStatus.pending,
    token: `invite_token_abc123xyz`,
    expiresAt: new Date(`2024-02-15T00:00:00Z`).toISOString(),
  }),
  new Invitation({
    orgId: OrgIds.acme,
    roleType: `member`,
    revokedAt: undefined,
    revokedBy: undefined,
    userId: UserIds.member,
    invitedBy: Ids.super.user,
    id: InvitationIds.accepted,
    email: `member@example.com`,
    token: `invite_token_def456uvw`,
    status: EInviteStatus.accepted,
    expiresAt: new Date(`2024-01-20T00:00:00Z`).toISOString(),
    acceptedAt: new Date(`2024-01-18T15:30:00Z`).toISOString(),
  }),
  new Invitation({
    userId: undefined,
    roleType: `admin`,
    revokedAt: undefined,
    revokedBy: undefined,
    acceptedAt: undefined,
    orgId: OrgIds.startup,
    invitedBy: Ids.super.user,
    id: InvitationIds.startup,
    status: EInviteStatus.pending,
    email: `developer@example.com`,
    token: `invite_token_ghi789rst`,
    expiresAt: new Date(`2024-02-10T00:00:00Z`).toISOString(),
  }),
  new Invitation({
    userId: undefined,
    roleType: `viewer`,
    revokedAt: undefined,
    revokedBy: undefined,
    acceptedAt: undefined,
    orgId: OrgIds.personal,
    invitedBy: UserIds.admin,
    id: InvitationIds.expired,
    email: `expired@example.com`,
    status: EInviteStatus.expired,
    token: `invite_token_jkl012mno`,
    expiresAt: new Date(`2024-01-01T00:00:00Z`).toISOString(),
  }),
  new Invitation({
    userId: undefined,
    roleType: `member`,
    orgId: OrgIds.acme,
    acceptedAt: undefined,
    invitedBy: Ids.super.user,
    revokedBy: Ids.super.user,
    id: InvitationIds.revoked,
    email: `revoked@example.com`,
    status: EInviteStatus.revoked,
    token: `invite_token_pqr345stu`,
    expiresAt: new Date(`2024-02-20T00:00:00Z`).toISOString(),
    revokedAt: new Date(`2024-01-25T10:00:00Z`).toISOString(),
  }),
]
