import { Secret } from '@tdsk/domain'
import { OrgIds, ProjectIds, SecretIds } from '@TDB/seeds/ids.seed'

export const secretsSeeds: Secret[] = [
  new Secret({
    orgId: OrgIds.acme,
    projectId: undefined,
    providerId: undefined,
    name: `Database Password`,
    hashKey: `hash_acme_db_pwd`,
    id: SecretIds.acmeDbPassword,
    description: `Production database password`,
    encryptedValue: `encrypted_acme_db_password_value`,
  }),
  new Secret({
    orgId: OrgIds.acme,
    projectId: undefined,
    providerId: undefined,
    name: `External API Key`,
    id: SecretIds.acmeApiKey,
    hashKey: `hash_acme_api_key`,
    description: `Third-party service API key`,
    encryptedValue: `encrypted_acme_api_key_value`,
  }),
  new Secret({
    orgId: undefined,
    name: `JWT Secret`,
    providerId: undefined,
    hashKey: `hash_acme_jwt`,
    projectId: ProjectIds.acmeApi,
    id: SecretIds.acmeProjectSecret,
    encryptedValue: `encrypted_jwt_secret_value`,
    description: `JWT signing secret for API project`,
  }),
  new Secret({
    projectId: undefined,
    providerId: undefined,
    orgId: OrgIds.startup,
    name: `Stripe API Key`,
    id: SecretIds.startupApiKey,
    hashKey: `hash_startup_stripe`,
    description: `Payment processor API key`,
    encryptedValue: `encrypted_stripe_key_value`,
  }),
  new Secret({
    orgId: undefined,
    providerId: undefined,
    name: `Anthropic API Key`,
    projectId: ProjectIds.acmeApi,
    hashKey: `hash_anthropic_key`,
    id: SecretIds.providerAnthropicKey,
    description: `Anthropic API authentication key`,
    encryptedValue: `encrypted_anthropic_key_value`,
  }),
  new Secret({
    name: `GitHub Token`,
    projectId: undefined,
    providerId: undefined,
    orgId: OrgIds.personal,
    id: SecretIds.personalToken,
    hashKey: `hash_github_token`,
    description: `Personal GitHub access token`,
    encryptedValue: `encrypted_github_token_value`,
  }),
]
