{{- if $.Values.customServiceAccount}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.customServiceAccount.name | quote }}
  labels:
    "app.kubernetes.io/name": "tdsk-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $.Values.customServiceAccount.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- range $annotationName, $annotationValue := $.Values.customServiceAccount.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
{{- if $.Values.customServiceAccount.imagePullSecret }}
imagePullSecrets:
  - name: {{ $.Values.customServiceAccount.imagePullSecret | quote }}
{{- end }}

---
{{- if $.Values.customServiceAccount.role}}
{{- $role := $.Values.customServiceAccount.role }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $role.name | quote }}
  labels:
    "app.kubernetes.io/name": "tdsk-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $role.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- range $annotationName, $annotationValue := $role.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
rules:
  - apiGroups: [""]
    resources:
    {{- range $resourceIndex, $resource := $role.resources }}
      - {{ $resource }}
    {{- end }}
    verbs:
    {{- range $verbIndex, $verb := $role.verbs }}
      - {{ $verb }}
    {{- end }}
---
{{- end }}
{{- if $.Values.customServiceAccount.binding }}
{{- $binding := $.Values.customServiceAccount.binding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $binding.name  | quote }}
  labels:
    "app.kubernetes.io/name": "tdsk-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $binding.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- range $annotationName, $annotationValue := $binding.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
{{- if $binding.subjects }}
subjects:
  - kind: {{ $binding.subjects.kind | default "ServiceAccount" | quote }}
    name: {{ $binding.subjects.name | default $.Values.customServiceAccount.name | quote }}
{{- else }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.customServiceAccount.name | quote }}
{{- end }}
{{- if $binding.ref }}
roleRef:
  kind: {{ $binding.ref.kind | default "Role" | quote }}
  name: {{ $binding.ref.name | default $.Values.customServiceAccount.role.name | quote }}
  apiGroup: {{ $binding.ref.group | default "rbac.authorization.k8s.io" | quote }}
{{- else }}
roleRef:
  kind: Role
  name: {{ $.Values.customServiceAccount.role.name | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
{{- end }}
{{- end }}