export { GhosttyVT } from './ghosttyVT'
export type { VTerminal } from './ghosttyVT'
export { ChangeDetector } from './changeDetector'
export { TerminalParser } from './terminalParser'
export { deriveToolState } from './deriveToolState'
export { PatternMatcherPipeline } from './patternMatcher'
export { claudeCodeMatchers } from './matchers/claudeCode'
export { getMatchers, registerMatchers } from './matchers'
