version: v2beta1
name: threadedstack


pipelines:

  # Disable the docker image build, it's handled externally
  build: null

  dev:
    run: |-
      ensure_pull_secrets --all
      run_pipelines start-px start-backend

  deploy:
    run: |-
      ensure_pull_secrets --all
      run_pipelines deploy-px deploy-backend

  deploy-px:
    run: |-
      create_deployments tdsk-proxy

  deploy-backend:
    run: |-
      create_deployments tdsk-backend

  start-px:
    run: |-
      create_deployments tdsk-proxy
      start_dev tdsk-proxy

  start-backend:
    run: |-
      create_deployments tdsk-backend
      start_dev tdsk-backend

vars:

# ----- General Values ----- #
  NODE_ENV:
    source: env
    default: local

  TDSK_HOST_DOMAIN:
    source: env
    default: local.threadedstack.app

# ----- Docker Image Values ----- #
  TDSK_IMAGE:
    source: env
    default: ghcr.io/threadedstack/tdsk-app
  TDSK_IMAGE_TAG:
    source: env
    default: latest


# ----- Proxy Values ----- #
  TDSK_PX_DEPLOYMENT:
    source: env
    default: tdsk-proxy
  TDSK_PX_IMAGE:
    source: env
    default: ghcr.io/threadedstack/tdsk-proxy
  TDSK_PX_IMAGE_TAG:
    source: env
    default: latest
  TDSK_PX_PORT:
    source: env
    default: 7118
  TDSK_PX_WS_PATH:
    source: env
    default: /tdsk-socket
  TDSK_PX_WS_DEBUG_PATH:
    source: env
    default: /devtools/page

# ----- Backend Values ----- #
  TDSK_BE_DEPLOYMENT:
    source: env
    default: tdsk-backend
  TDSK_BE_IMAGE:
    source: env
    default: ghcr.io/threadedstack/tdsk-backend
  TDSK_BE_IMAGE_TAG:
    source: env
    default: latest
  TDSK_BE_PORT:
    source: env
    default: 7119

# ----- Kubernetes Secrets ----- #
  TDSK_KUBE_SCRT_DOC_AUTH:
    source: env
    default: docker-auth
  TDSK_KUBE_SCRT_DB_CFG:
    source: env
    default: tdsk-db-cfg
  TDSK_KUBE_SCRT_TLS_NAME:
    source: env
    default: tdsk-tls-secret
  TDSK_KUBE_SCRT_MASTER_KEY:
    source: env
    default: tdsk-master-key

# ----- Server Configuration ----- #
  TDSK_ALLOWED_HEADERS:
    source: env
    default: 'X-PINGOTHER,Origin,X-Requested-With,Content-Type,Accept,Authorization,AuthToken,x-tdsk-host,x-tdsk-proto,x-tdsk-port,x-tdsk-route,x-tdsk-job-id,x-tdsk-subdomain,x-forwarded-subdomain,x-forwarded-port,x-forwarded-proto,x-forwarded-host,x-forwarded-for'
  TDSK_SERVER_ORIGINS:
    source: env
    default: 'http://localhost:7117,localhost,threadedstack.app,dev.threadedstack.app,threadedstack-develop.local.keghub.io,proxy.dev.threadedstack.app,http://0.0.0.0'



images:
  tdsk-app:
    image: ${TDSK_IMAGE}
    createPullSecret: true
    injectRestartHelper: false
    tags:
    - '${TDSK_IMAGE_TAG}'
    - '####-${NODE_ENV}-${devspace.git.commit}'
    dockerfile: ./Dockerfile
    context: ../


# This is a list of `deployments` that DevSpace can create for this project
deployments:

  tdsk-proxy:
    helm:
      upgradeArgs:
        - "--force"
      chart:
        name: ./
      valuesFiles:
        - ./values.empty.yaml
      values:
        containers:
          - name: ${TDSK_PX_DEPLOYMENT}
            image: ${TDSK_PX_IMAGE}:${TDSK_PX_IMAGE_TAG}
            imagePullPolicy: IfNotPresent
            env:
            - name: TDSK_SUB_REPO
              value: proxy
            - name: TDSK_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  key: token
                  name: ${TDSK_KUBE_SCRT_MASTER_KEY}
                  optional: false
            - name: TDSK_DB_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: false
            - name: TDSK_DB_TYPE
              valueFrom:
                secretKeyRef:
                  key: type
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: false
            - name: TDSK_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: name
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: false
            - name: TDSK_DB_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_JWT_SCRT
              valueFrom:
                secretKeyRef:
                  key: jwt
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  key: project
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_SRV_ROLE
              valueFrom:
                secretKeyRef:
                  key: role
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true

        service:
          name: ${TDSK_PX_DEPLOYMENT}
          ports:
            - port: ${TDSK_PX_PORT}
          annotations:
            service.beta.kubernetes.io/threaded-stack-default-protocol: http
            service.beta.kubernetes.io/threaded-stack-port-443: '{"tls-secret-name": "tdsk-tls-secret", "protocol": "https"}'
        ingress:
          tls: false
          labels: null
          name: ${TDSK_PX_DEPLOYMENT}-ingress
          annotations:
            nginx.ingress.kubernetes.io/affinity: cookie
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: 8m
            nginx.ingress.kubernetes.io/proxy-redirect: "off"
            nginx.ingress.kubernetes.io/affinity-mode: persistent
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "75"
            nginx.ingress.kubernetes.io/cors-allow-origin: ${TDSK_SERVER_ORIGINS}
            nginx.ingress.kubernetes.io/cors-allow-headers: ${TDSK_ALLOWED_HEADERS}
            nginx.ingress.kubernetes.io/cors-allow-methods: GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "X-TDSK-Host: $http_x_tdsk_host";
              more_set_headers "X-TDSK-Port: $http_x_tdsk_port";
              more_set_headers "X-TDSK-Route: $http_x_tdsk_route";
              more_set_headers "X-TDSK-Proto: $http_x_tdsk_proto";
              more_set_headers "X-TDSK-Subdomain: $http_x_tdsk_subdomain";
              proxy_set_header Authorization $http_authorization;
          rules:
            - host: px.${TDSK_HOST_DOMAIN}
              path: /
              pathType: ImplementationSpecific
              serviceName: ${TDSK_PX_DEPLOYMENT}
              servicePort: ${TDSK_PX_PORT}
            - host: px.${TDSK_HOST_DOMAIN}
              path: ${TDSK_PX_WS_PATH}
              pathType: ImplementationSpecific
              serviceName: ${TDSK_PX_DEPLOYMENT}
              servicePort: ${TDSK_PX_PORT}
            - host: px.${TDSK_HOST_DOMAIN}
              path: ${TDSK_PX_WS_DEBUG_PATH}
              pathType: ImplementationSpecific
              serviceName: ${TDSK_PX_DEPLOYMENT}
              servicePort: ${TDSK_PX_PORT}
            - host: '*.px.${TDSK_HOST_DOMAIN}'
              path: /
              pathType: ImplementationSpecific
              serviceName: ${TDSK_PX_DEPLOYMENT}
              servicePort: ${TDSK_PX_PORT}
            - host: '*.px.${TDSK_HOST_DOMAIN}'
              path: ${TDSK_PX_WS_PATH}
              pathType: ImplementationSpecific
              serviceName: ${TDSK_PX_DEPLOYMENT}
              servicePort: ${TDSK_PX_PORT}
            - host: '*.px.${TDSK_HOST_DOMAIN}'
              path: ${TDSK_PX_WS_DEBUG_PATH}
              pathType: ImplementationSpecific
              serviceName: ${TDSK_PX_DEPLOYMENT}
              servicePort: ${TDSK_PX_PORT}


  tdsk-backend:
    helm:
      upgradeArgs:
        - "--force"
      chart:
        name: ./
      valuesFiles:
        - ./values.yaml
        - ./values.${NODE_ENV}.yaml
      values:
        litellm:
          enabled: false
        containers:
          - name: ${TDSK_BE_DEPLOYMENT}
            image: ${TDSK_BE_IMAGE}:${TDSK_BE_IMAGE_TAG}
            imagePullPolicy: IfNotPresent
            env:
            - name: TDSK_SUB_REPO
              value: backend
            - name: TDSK_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  key: token
                  name: ${TDSK_KUBE_SCRT_MASTER_KEY}
                  optional: false
            - name: TDSK_DB_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: false
            - name: TDSK_DB_TYPE
              valueFrom:
                secretKeyRef:
                  key: type
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: false
            - name: TDSK_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: name
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: false
            - name: TDSK_DB_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_JWT_SCRT
              valueFrom:
                secretKeyRef:
                  key: jwt
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  key: project
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
            - name: TDSK_DB_SRV_ROLE
              valueFrom:
                secretKeyRef:
                  key: role
                  name: ${TDSK_KUBE_SCRT_DB_CFG}
                  optional: true
                  
        service:
          name: ${TDSK_BE_DEPLOYMENT}
          ports:
            - port: ${TDSK_BE_PORT}
        ingress:
          tls: false
          labels: null
          name: ${TDSK_BE_DEPLOYMENT}-ingress
          rules:
            - host: be.${TDSK_HOST_DOMAIN}
              serviceName: ${TDSK_BE_DEPLOYMENT}
              servicePort: ${TDSK_BE_PORT}
            - host: '*.be.${TDSK_HOST_DOMAIN}'
              serviceName: ${TDSK_BE_DEPLOYMENT}
              servicePort: ${TDSK_BE_PORT}


# This is a list of `dev` containers that are based on the containers created by your deployments
dev:


  tdsk-proxy:
    labelSelector:
      app.kubernetes.io/component: ${TDSK_PX_DEPLOYMENT}
    devImage: ghcr.io/threadedstack/tdsk-app:latest
    logs: {}
    sync:
      - path: ../:/tdsk
        excludePaths:
          - .*
          - '**'
          - '!/deploy'
          - '!/configs'
          - '!/repos/proxy'
          - '!/repos/logger'
          - '!/repos/domain'
          - '!/tsconfig.json'
          - '!/repos/database'
          - /repos/proxy/dist
          - /repos/logger/dist
          - /repos/domain/dist
          - /repos/database/dist
          - node_modules
          - node_modules/**
          - deploy/scripts
          - deploy/.devspace
          - deploy/templates
        printLogs: true
        waitInitialSync: true
        disableDownload: true
        initialSync: mirrorLocal
    ssh:
      enabled: true
    ports:
      - port: ${TDSK_PX_PORT}

  tdsk-backend:
    labelSelector:
      app.kubernetes.io/component: ${TDSK_BE_DEPLOYMENT}
    devImage: ghcr.io/threadedstack/tdsk-app:latest
    logs: {}
    sync:
      - path: ../:/tdsk
        excludePaths:
          - .*
          - '**'
          - '!/deploy'
          - '!/configs'
          - '!/repos/backend'
          - '!/repos/logger'
          - '!/repos/domain'
          - '!/tsconfig.json'
          - '!/repos/database'
          - /repos/backend/dist
          - /repos/logger/dist
          - /repos/domain/dist
          - /repos/database/dist
          - node_modules
          - node_modules/**
          - deploy/scripts
          - deploy/.devspace
          - deploy/templates
        printLogs: true
        waitInitialSync: true
        disableDownload: true
        initialSync: mirrorLocal
    ssh:
      enabled: true
    ports:
      - port: ${TDSK_BE_PORT}


# Use profile to dynamically set options based on the environment
profiles:
- name: local
  patches:
  - op: replace
    path: deployments.tdsk-proxy.helm.values.containers[0].image
    value: ${TDSK_IMAGE}:${TDSK_IMAGE_TAG}
  - op: replace
    path: deployments.tdsk-backend.helm.values.containers[0].image
    value: ${TDSK_IMAGE}:${TDSK_IMAGE_TAG}
- name: production
