# Values only loaded in a local environment, when NODE_ENV === 'local'
env:

  # ---- Shared ENVs ---- #
  NODE_ENV: local
  DEVSPACE_INJECT_LOCAL: true
  TDSK_KUBE_NAMESPACE: tdsk-local
  TDSK_KUBE_CONTEXT: docker-desktop
  TDSK_CADDY_PX_HOST: px.local.threadedstack.app

  # Disable logger hiding
  STL_FORCE_DISABLE_SAFE: true
  