import { camelCase } from '@keg-hub/jsutils'

export type TTemplateOpts = {
  name:string
  exports: string[]
  imports: string[]
  worldName:string
}

/**
 * Generate the runWasm template
 */
export const template = (opts:TTemplateOpts) => {
  const {
    name,
    imports, 
    exports,
    worldName,
  } = opts

  // Generate TypeScript type for exports
  const exportsType = exports.length > 0
    ? `{\n${exports.map(exp => `  ${exp}: (...args: any[]) => any`).join('\n')}\n}`
    : `Record<string, any>`

  // Generate exports interface comment
  const exportsComment = exports.length > 0
    ? `// Available exports: ${exports.join(`, `)}`
    : `// No exports found in WIT definition`

  const camelName = camelCase(name)
  
  return `/**
 * Auto-generated runWasm helper for ${name}
 *
 * This file is automatically generated by @TWA/builders/generateRunWasm
 * DO NOT EDIT MANUALLY - changes will be overwritten on next build
 *
 * Generated from world: ${worldName}
 * ${exportsComment}
 *
 * @module ${name}.run
 */

import { join, dirname } from 'node:path'
import { readFile } from 'node:fs/promises'

/**
 * Options for running the ${name} WASM module
 */
export interface ${camelName}RunOpts {
  /** Custom imports to merge with default imports */
  imports?: Record<string, any>
  /** Enable debug logging */
  logging?: boolean
}

/**
 * Result from instantiating the ${name} WASM module
 */
export interface ${camelName}Instance {
  /** Exported functions from WASM module */
  exports: ${exportsType}
  /** Imports that were passed to instantiate */
  imports: Record<string, any>
${exports.map(exp => `  /** ${exp} export */`).join('\n')}
  ${exports.join(', ')}: any
}

/**
 * Run the ${name} WASM module with proper core module loading
 *
 * This function handles the complexity of loading jco-generated WASM modules
 * by providing the correct getCoreModule implementation for Node.js environments.
 *
 * @param options - Configuration options
 * @returns Promise resolving to the WASM instance
 *
 * @example
 * \`\`\`typescript
 * import { run${camelName} } from './${name}.run.js'
 *
 * const instance = await run${camelName}({
 *   imports: {
 *     'local:tdsk/host-callback': {
 *       onToken: (token) => console.log(token)
 *     }
 *   },
 *   logging: true
 * })
 *
 * // Call exported function
 * await instance.${exports[0] || 'processRequest'}('Hello')
 * \`\`\`
 */
export async function run${camelName}(
  options: ${camelName}RunOpts = {}
): Promise<${camelName}Instance> {
  const { imports = {}, logging = false } = options

  const log = (...args: unknown[]) => logging && console.log('[${name}.run]', ...args)

  try {
    // Import the jco-generated bindings
    // This file is in the same directory as this run file
    const moduleDir = dirname(__dirname) // Go up to dist/wasm
    const wasmModule = await import(join(moduleDir, '${name}.js'))

    if (typeof wasmModule.instantiate !== 'function') {
      throw new Error(
        'WASM module does not export an instantiate function. ' +
        'Make sure the module was built with jco --instantiation flag.'
      )
    }

    log('Loading WASM module from:', join(moduleDir, '${name}.js'))

    // Provide custom getCoreModule for Node.js filesystem loading
    // jco expects this function to return compiled WebAssembly.Module objects
    const getCoreModule = async (coreFileName: string): Promise<WebAssembly.Module> => {
      const corePath = join(moduleDir, coreFileName)
      log('Loading core module:', corePath)

      try {
        const coreBuffer = await readFile(corePath) as BufferSource
        return WebAssembly.compile(coreBuffer)
      } catch (error) {
        throw new Error(
          \`Failed to load core module \${coreFileName}: \${error}\`
        )
      }
    }

    log('Instantiating WASM with custom imports...')
    log('Import interfaces:', ${JSON.stringify(imports)})

    // Instantiate the WASM component
    const instance = await wasmModule.instantiate(getCoreModule, imports)

    log('WASM instantiated successfully')
    log('Available exports:', Object.keys(instance))

${exports.length > 0 ? exports.map(exp => `    // Type-safe access to ${exp} export
    if (typeof instance.${exp} !== 'function') {
      throw new Error(\`WASM module missing export: ${exp}\`)
    }
`).join('\n') : '    // No typed exports found\n'}

    return {
      exports: instance,
      imports: imports,
${exports.map(exp => `      ${exp}: instance.${exp},`).join('\n')}
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    log('ERROR:', message)
    throw new Error(\`Failed to run ${name} WASM: \${message}\`)
  }
}

/**
 * Convenience function to run a specific export
 *
 * @param exportName - Name of the export to call (e.g., 'processRequest')
 * @param args - Arguments to pass to the export function
 * @param options - Configuration options
 * @returns Promise resolving to the result
 */
export async function runExport(
  exportName: string,
  args: any[] = [],
  options?: ${camelName}RunOpts
): Promise<any> {
  const instance = await run${camelName}(options)

  if (typeof instance.exports[exportName] !== 'function') {
    throw new Error(\`Export "\${exportName}" not found or not a function\`)
  }

  return instance.exports[exportName](...args)
}
`
}


/**
 * Generate a generic runner when WIT parsing fails
 */
export const genericTemplate = (name: string): string => {
  const camelName = camelCase(name)

  return `/**
 * Auto-generated runWasm helper for ${name}
 *
 * This is a generic runner without type information.
 * For full type safety, ensure WIT files are properly configured.
 *
 * @module ${name}.run
 */

import { join, dirname } from 'node:path'
import { readFile } from 'node:fs/promises'

export interface ${camelName}RunOpts {
  imports?: Record<string, any>
  logging?: boolean
}

export interface ${camelName}Instance {
  exports: Record<string, any>
  imports: Record<string, any>
}

export async function run${camelName}(
  options: ${camelName}RunOpts = {}
): Promise<${camelName}Instance> {
  const { imports = {}, logging = false } = options

  const log = (...args: unknown[]) => logging && console.log('[${name}.run]', ...args)

  try {
    const moduleDir = dirname(__dirname)
    const wasmModule = await import(join(moduleDir, '${name}.js'))

    if (typeof wasmModule.instantiate !== 'function') {
      throw new Error(
        'WASM module does not export an instantiate function'
      )
    }

    const getCoreModule = async (coreFileName: string): Promise<WebAssembly.Module> => {
      const corePath = join(moduleDir, coreFileName)
      log('Loading core module:', corePath)

      const coreBuffer = await readFile(corePath) as BufferSource
      return WebAssembly.compile(coreBuffer)
    }

    log('Instantiating WASM...')
    const instance = await wasmModule.instantiate(getCoreModule, imports)

    log('WASM instantiated successfully')
    log('Available exports:', Object.keys(instance))

    return {
      exports: instance,
      imports: imports,
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    log('ERROR:', message)
    throw new Error(\`Failed to run ${name} WASM: \${message}\`)
  }
}
`
}
