import { wordCaps } from '@keg-hub/jsutils/wordCaps'
import { camelCase } from '@keg-hub/jsutils/camelCase'

export type TTemplateOpts = {
  name: string
  exports: string[]
  imports: string[]
  worldName: string
}

/**
 * Generate the runWasm template
 */
export const template = (opts: TTemplateOpts) => {
  const { name, imports, exports, worldName } = opts

  // Generate TypeScript type for exports
  const exportsType =
    exports.length > 0
      ? `{\n${exports.map((exp) => `  ${exp}: (...args: any[]) => any`).join('\n')}\n}`
      : `Record<string, any>`

  // Generate exports interface comment
  const exportsComment =
    exports.length > 0
      ? `// Available exports: ${exports.join(`, `)}`
      : `// No exports found in WIT definition`

  const capsName = wordCaps(name)
  const camelName = camelCase(name)

  return `/**
 * Auto-generated runWasm helper for ${name}
 *
 * This file is automatically generated by @TWA/builders/generateRunWasm
 * DO NOT EDIT MANUALLY - changes will be overwritten on next build
 *
 * Generated from world: ${worldName}
 * ${exportsComment}
 *
 * @module ${name}.run
 */

import type {
  WASIImportObject,
  VersionedWASIImportObject,
} from '@bytecodealliance/preview2-shim/instantiation'

import { join, dirname } from 'node:path'
import { readFile } from 'node:fs/promises'
import { WASIShim } from '@bytecodealliance/preview2-shim/instantiation'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Create preview2-shim instance for default WASI imports
const wss = new WASIShim()
const shim: WASIImportObject = wss.getImportObject()
shim satisfies WASIImportObject
shim satisfies VersionedWASIImportObject<''>

/**
 * Options for running the ${name} WASM module
 */
export interface ${capsName}RunOpts {
  /** Custom imports to merge with default WASI imports */
  imports?: Record<string, any>
  /** Arguments to pass to the WASM module */
  args?: string[]
  /** Environment variables to pass to the WASM module */
  env?: Record<string, string>
  /** Preopened directories for filesystem access */
  preopens?: Record<string, string>
  /** Enable debug logging */
  logging?: boolean
}

/**
 * Result from instantiating the ${name} WASM module
 */
export interface ${capsName}Instance {
  /** Exported functions from WASM module */
  exports: ${exportsType}
  /** Imports that were passed to instantiate */
  imports: Record<string, any>
${exports.map((exp) => `  /** ${exp} export */`).join('\n')}
  ${exports.join(', ')}: any
}

/**
 * Run the ${name} WASM module with proper core module loading
 *
 * This function handles the complexity of loading jco-generated WASM modules
 * by providing the correct getCoreModule implementation for Node.js environments.
 *
 * @param options - Configuration options
 * @returns Promise resolving to the WASM instance
 *
 * @example
 * \`\`\`typescript
 * import { run${camelName} } from './${name}.run.js'
 *
 * const instance = await run${camelName}({
 *   imports: {
 *     'local:tdsk/host-callback': {
 *       onToken: (token) => console.log(token)
 *     }
 *   },
 *   env: { HOME: '/tmp' },
 *   preopens: { '/data': './data' },
 *   logging: true
 * })
 *
 * // Call exported function
 * await instance.${exports[0] || 'processRequest'}('Hello')
 * \`\`\`
 */
export async function run${camelName}(
  options: ${capsName}RunOpts = {}
): Promise<${capsName}Instance> {
  const {
    imports: customImports = {},
    args = [],
    env = {},
    preopens = {},
    logging = false
  } = options

  const log = (...args: unknown[]) => logging && console.log('[${name}.run]', ...args)

  try {
    // Import the jco-generated bindings
    // This file is in the same directory as this run file
    const wasmModule = await import(join(__dirname, '${name}.js'))

    if (typeof wasmModule.instantiate !== 'function') {
      throw new Error(
        'WASM module does not export an instantiate function. ' +
        'Make sure the module was built with jco --instantiation flag.'
      )
    }

    log('Loading WASM module from:', join(__dirname, '${name}.js'))

    // Provide custom getCoreModule for Node.js filesystem loading
    // jco expects this function to return compiled WebAssembly.Module objects
    const getCoreModule = async (coreFileName: string): Promise<WebAssembly.Module> => {
      const corePath = join(__dirname, coreFileName)
      log('Loading core module:', corePath)

      try {
        const coreBuffer = await readFile(corePath) as BufferSource
        return WebAssembly.compile(coreBuffer)
      } catch (error) {
        throw new Error(
          \`Failed to load core module \${coreFileName}: \${error}\`
        )
      }
    }

    // Merge default preview2-shim imports with custom imports
    // Custom imports override defaults (shallow merge)
    const mergedImports: typeof shim = {
      ...shim,
      ...customImports,
    }

    // Configure environment variables if provided
    if (Object.keys(env).length > 0) {
      log('Setting environment variables:', Object.keys(env))
      // @ts-ignore - preview2-shim types may not include setEnvironment
      const envImport = mergedImports['wasi:cli/environment']
      if (envImport && typeof envImport.getEnvironment === 'function') {
        // Note: Environment handling depends on shim interface
        log('Environment variables configured (see shim-specific interface)')
      }
    }

    // Configure preopens for filesystem access if provided
    if (Object.keys(preopens).length > 0) {
      log('Setting preopens:', Object.keys(preopens))
      // @ts-ignore - preview2-shim types may not include setPreopens
      const preopensImport = mergedImports['wasi:filesystem/preopens']
      if (preopensImport && typeof preopensImport.getDirectories === 'function') {
        // Convert preopens object to [[guestPath, { hostPath }], ...] format
        const directories = Object.entries(preopens).map(([guestPath, hostPath]) => [
          guestPath,
          { hostPath: String(hostPath) },
        ])
        // Note: Preopens handling depends on shim interface
        log('Preopens configured (see shim-specific interface)')
      }
    }

    log('Instantiating WASM with merged imports...')
    log('Custom imports:', Object.keys(customImports))
    if (args.length > 0) log('Arguments:', args)

    // Instantiate the WASM component
    const instance = await wasmModule.instantiate(getCoreModule, mergedImports)

    log('WASM instantiated successfully')
    log('Available exports:', Object.keys(instance))

${
  exports.length > 0
    ? exports
        .map(
          (exp) => `    // Type-safe access to ${exp} export
    if (typeof instance.${exp} !== 'function') {
      throw new Error(\`WASM module missing export: ${exp}\`)
    }
`
        )
        .join('\n')
    : '    // No typed exports found\n'
}

    return {
      exports: instance,
      imports: mergedImports,
${exports.map((exp) => `      ${exp}: instance.${exp},`).join('\n')}
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    log('ERROR:', message)
    throw new Error(\`Failed to run ${name} WASM: \${message}\`)
  }
}

/**
 * Convenience function to run a specific export
 *
 * @param exportName - Name of the export to call (e.g., 'processRequest')
 * @param args - Arguments to pass to the export function
 * @param options - Configuration options
 * @returns Promise resolving to the result
 */
export async function runExport(
  exportName: string,
  args: any[] = [],
  options?: ${capsName}RunOpts
): Promise<any> {
  const instance = await run${camelName}(options)

  if (typeof instance.exports[exportName] !== 'function') {
    throw new Error(\`Export "\${exportName}" not found or not a function\`)
  }

  return instance.exports[exportName](...args)
}
`
}

/**
 * Generate a generic runner when WIT parsing fails
 */
export const genericTemplate = (name: string): string => {
  const capsName = wordCaps(name)
  const camelName = camelCase(name)

  return `/**
 * Auto-generated runWasm helper for ${name}
 *
 * This is a generic runner without type information.
 * For full type safety, ensure WIT files are properly configured.
 *
 * @module ${name}.run
 */

import type {
  WASIImportObject,
  VersionedWASIImportObject,
} from '@bytecodealliance/preview2-shim/instantiation'

import { join, dirname } from 'node:path'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { WASIShim } from '@bytecodealliance/preview2-shim/instantiation'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Create preview2-shim instance for default WASI imports
const wss = new WASIShim()
const shim: WASIImportObject = wss.getImportObject()
shim satisfies WASIImportObject
shim satisfies VersionedWASIImportObject<''>

export interface ${capsName}RunOpts {
  imports?: Record<string, any>
  args?: string[]
  env?: Record<string, string>
  preopens?: Record<string, string>
  logging?: boolean
}

export interface ${capsName}Instance {
  exports: Record<string, any>
  imports: Record<string, any>
}

export async function run${camelName}(
  options: ${capsName}RunOpts = {}
): Promise<${capsName}Instance> {
  const {
    imports: customImports = {},
    args = [],
    env = {},
    preopens = {},
    logging = false
  } = options

  const log = (...args: unknown[]) => logging && console.log('[${name}.run]', ...args)

  try {
    const wasmModule = await import(join(__dirname, '${name}.js'))

    if (typeof wasmModule.instantiate !== 'function') {
      throw new Error(
        'WASM module does not export an instantiate function'
      )
    }

    const getCoreModule = async (coreFileName: string): Promise<WebAssembly.Module> => {
      const corePath = join(__dirname, coreFileName)
      log('Loading core module:', corePath)

      const coreBuffer = await readFile(corePath) as BufferSource
      return WebAssembly.compile(coreBuffer)
    }

    // Merge default preview2-shim imports with custom imports
    const mergedImports: typeof shim = {
      ...shim,
      ...customImports,
    }

    // Configure environment and preopens if provided
    if (Object.keys(env).length > 0) {
      log('Setting environment variables:', Object.keys(env))
    }

    if (Object.keys(preopens).length > 0) {
      log('Setting preopens:', Object.keys(preopens))
    }

    log('Instantiating WASM...')
    const instance = await wasmModule.instantiate(getCoreModule, mergedImports)

    log('WASM instantiated successfully')
    log('Available exports:', Object.keys(instance))

    return {
      exports: instance,
      imports: mergedImports,
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    log('ERROR:', message)
    throw new Error(\`Failed to run ${name} WASM: \${message}\`)
  }
}
`
}
