import type { ITheme } from '@xterm/xterm'
import type { TTerminalSettings, TTerminalThemePreset } from '@TTH/types/terminal.types'

export const HeaderHeight = 50
export const TabBarHeight = 40
export const ContentPadding = 16
export const SessionHeaderHeight = 48
export const PagePadding = 64 + ContentPadding

export const TerminalFontOptions = [
  { label: `JetBrains Mono`, value: `'JetBrains Mono', monospace` },
  { label: `Fira Code`, value: `'Fira Code', monospace` },
  { label: `Cascadia Code`, value: `'Cascadia Code', monospace` },
  { label: `Source Code Pro`, value: `'Source Code Pro', monospace` },
  { label: `Inconsolata`, value: `'Inconsolata', monospace` },
  { label: `IBM Plex Mono`, value: `'IBM Plex Mono', monospace` },
  { label: `System Monospace`, value: `monospace` },
] as const

export const TerminalFontSizeRange = { min: 8, max: 28, step: 1 } as const
export const TerminalScrollbackRange = { min: 1000, max: 100_000, step: 1000 } as const
export const TerminalSmoothScrollRange = { min: 0, max: 500, step: 10 } as const

export const TerminalCursorStyles = [
  { label: `Block`, value: `block` },
  { label: `Underline`, value: `underline` },
  { label: `Bar`, value: `bar` },
] as const

const threadedStack: ITheme = {
  background: `#1A1D21`,
  foreground: `#CECECE`,
  cursor: `#3370DE`,
  cursorAccent: `#1A1D21`,
  selectionBackground: `#214A92`,
  selectionForeground: `#E6E6E6`,
  black: `#21252B`,
  red: `#EF4444`,
  green: `#2cb67d`,
  yellow: `#F59E0B`,
  blue: `#3370DE`,
  magenta: `#B48EAD`,
  cyan: `#4FC3F7`,
  white: `#CECECE`,
  brightBlack: `#767676`,
  brightRed: `#F87171`,
  brightGreen: `#34D399`,
  brightYellow: `#FBBF24`,
  brightBlue: `#60A5FA`,
  brightMagenta: `#C4A7D7`,
  brightCyan: `#67D9FB`,
  brightWhite: `#E6E6E6`,
}

const catppuccinMocha: ITheme = {
  background: `#1e1e2e`,
  foreground: `#cdd6f4`,
  cursor: `#f5e0dc`,
  cursorAccent: `#1e1e2e`,
  selectionBackground: `#45475a`,
  selectionForeground: `#cdd6f4`,
  black: `#45475a`,
  red: `#f38ba8`,
  green: `#a6e3a1`,
  yellow: `#f9e2af`,
  blue: `#89b4fa`,
  magenta: `#f5c2e7`,
  cyan: `#94e2d5`,
  white: `#bac2de`,
  brightBlack: `#585b70`,
  brightRed: `#f38ba8`,
  brightGreen: `#a6e3a1`,
  brightYellow: `#f9e2af`,
  brightBlue: `#89b4fa`,
  brightMagenta: `#f5c2e7`,
  brightCyan: `#94e2d5`,
  brightWhite: `#a6adc8`,
}

const dracula: ITheme = {
  background: `#282a36`,
  foreground: `#f8f8f2`,
  cursor: `#f8f8f2`,
  cursorAccent: `#282a36`,
  selectionBackground: `#44475a`,
  selectionForeground: `#f8f8f2`,
  black: `#21222c`,
  red: `#ff5555`,
  green: `#50fa7b`,
  yellow: `#f1fa8c`,
  blue: `#bd93f9`,
  magenta: `#ff79c6`,
  cyan: `#8be9fd`,
  white: `#f8f8f2`,
  brightBlack: `#6272a4`,
  brightRed: `#ff6e6e`,
  brightGreen: `#69ff94`,
  brightYellow: `#ffffa5`,
  brightBlue: `#d6acff`,
  brightMagenta: `#ff92df`,
  brightCyan: `#a4ffff`,
  brightWhite: `#ffffff`,
}

const oneDark: ITheme = {
  background: `#282c34`,
  foreground: `#abb2bf`,
  cursor: `#528bff`,
  cursorAccent: `#282c34`,
  selectionBackground: `#3e4451`,
  selectionForeground: `#abb2bf`,
  black: `#5c6370`,
  red: `#e06c75`,
  green: `#98c379`,
  yellow: `#e5c07b`,
  blue: `#61afef`,
  magenta: `#c678dd`,
  cyan: `#56b6c2`,
  white: `#abb2bf`,
  brightBlack: `#4b5263`,
  brightRed: `#be5046`,
  brightGreen: `#98c379`,
  brightYellow: `#d19a66`,
  brightBlue: `#61afef`,
  brightMagenta: `#c678dd`,
  brightCyan: `#56b6c2`,
  brightWhite: `#ffffff`,
}

const solarizedDark: ITheme = {
  background: `#002b36`,
  foreground: `#839496`,
  cursor: `#839496`,
  cursorAccent: `#002b36`,
  selectionBackground: `#073642`,
  selectionForeground: `#93a1a1`,
  black: `#073642`,
  red: `#dc322f`,
  green: `#859900`,
  yellow: `#b58900`,
  blue: `#268bd2`,
  magenta: `#d33682`,
  cyan: `#2aa198`,
  white: `#eee8d5`,
  brightBlack: `#002b36`,
  brightRed: `#cb4b16`,
  brightGreen: `#586e75`,
  brightYellow: `#657b83`,
  brightBlue: `#839496`,
  brightMagenta: `#6c71c4`,
  brightCyan: `#93a1a1`,
  brightWhite: `#fdf6e3`,
}

const solarizedLight: ITheme = {
  background: `#fdf6e3`,
  foreground: `#657b83`,
  cursor: `#657b83`,
  cursorAccent: `#fdf6e3`,
  selectionBackground: `#eee8d5`,
  selectionForeground: `#586e75`,
  black: `#073642`,
  red: `#dc322f`,
  green: `#859900`,
  yellow: `#b58900`,
  blue: `#268bd2`,
  magenta: `#d33682`,
  cyan: `#2aa198`,
  white: `#eee8d5`,
  brightBlack: `#002b36`,
  brightRed: `#cb4b16`,
  brightGreen: `#586e75`,
  brightYellow: `#657b83`,
  brightBlue: `#839496`,
  brightMagenta: `#6c71c4`,
  brightCyan: `#93a1a1`,
  brightWhite: `#fdf6e3`,
}

const githubDark: ITheme = {
  background: `#0d1117`,
  foreground: `#c9d1d9`,
  cursor: `#c9d1d9`,
  cursorAccent: `#0d1117`,
  selectionBackground: `#264f78`,
  selectionForeground: `#ffffff`,
  black: `#484f58`,
  red: `#ff7b72`,
  green: `#3fb950`,
  yellow: `#d29922`,
  blue: `#58a6ff`,
  magenta: `#bc8cff`,
  cyan: `#39c5cf`,
  white: `#b1bac4`,
  brightBlack: `#6e7681`,
  brightRed: `#ffa198`,
  brightGreen: `#56d364`,
  brightYellow: `#e3b341`,
  brightBlue: `#79c0ff`,
  brightMagenta: `#d2a8ff`,
  brightCyan: `#56d4dd`,
  brightWhite: `#f0f6fc`,
}

const nord: ITheme = {
  background: `#2e3440`,
  foreground: `#d8dee9`,
  cursor: `#d8dee9`,
  cursorAccent: `#2e3440`,
  selectionBackground: `#434c5e`,
  selectionForeground: `#eceff4`,
  black: `#3b4252`,
  red: `#bf616a`,
  green: `#a3be8c`,
  yellow: `#ebcb8b`,
  blue: `#81a1c1`,
  magenta: `#b48ead`,
  cyan: `#88c0d0`,
  white: `#e5e9f0`,
  brightBlack: `#4c566a`,
  brightRed: `#bf616a`,
  brightGreen: `#a3be8c`,
  brightYellow: `#ebcb8b`,
  brightBlue: `#81a1c1`,
  brightMagenta: `#b48ead`,
  brightCyan: `#8fbcbb`,
  brightWhite: `#eceff4`,
}

export const TerminalThemePresets: Record<
  Exclude<TTerminalThemePreset, 'custom'>,
  ITheme
> = {
  threadedstack: threadedStack,
  'catppuccin-mocha': catppuccinMocha,
  dracula: dracula,
  'one-dark': oneDark,
  'solarized-dark': solarizedDark,
  'solarized-light': solarizedLight,
  'github-dark': githubDark,
  nord: nord,
}

export const TerminalThemePresetLabels: Record<TTerminalThemePreset, string> = {
  threadedstack: `ThreadedStack`,
  'catppuccin-mocha': `Catppuccin Mocha`,
  dracula: `Dracula`,
  'one-dark': `One Dark`,
  'solarized-dark': `Solarized Dark`,
  'solarized-light': `Solarized Light`,
  'github-dark': `GitHub Dark`,
  nord: `Nord`,
  custom: `Custom`,
}

export const DefaultTerminalSettings: TTerminalSettings = {
  fontSize: 14,
  fontFamily: `'JetBrains Mono', monospace`,
  cursorStyle: `bar`,
  cursorBlink: true,
  scrollback: 10_000,
  smoothScrollDuration: 100,
  allowTransparency: false,
  themePreset: `threadedstack`,
  theme: threadedStack,
}

export const TerminalThemeColorFields = [
  { key: `foreground`, label: `Foreground` },
  { key: `background`, label: `Background` },
  { key: `cursor`, label: `Cursor` },
  { key: `cursorAccent`, label: `Cursor Accent` },
  { key: `selectionBackground`, label: `Selection BG` },
  { key: `selectionForeground`, label: `Selection FG` },
  { key: `black`, label: `Black` },
  { key: `red`, label: `Red` },
  { key: `green`, label: `Green` },
  { key: `yellow`, label: `Yellow` },
  { key: `blue`, label: `Blue` },
  { key: `magenta`, label: `Magenta` },
  { key: `cyan`, label: `Cyan` },
  { key: `white`, label: `White` },
  { key: `brightBlack`, label: `Bright Black` },
  { key: `brightRed`, label: `Bright Red` },
  { key: `brightGreen`, label: `Bright Green` },
  { key: `brightYellow`, label: `Bright Yellow` },
  { key: `brightBlue`, label: `Bright Blue` },
  { key: `brightMagenta`, label: `Bright Magenta` },
  { key: `brightCyan`, label: `Bright Cyan` },
  { key: `brightWhite`, label: `Bright White` },
] as const
