package local:shell;

world shell {
  include wasi:cli/imports@0.2.0;
  include wasi:sockets/imports@0.2.0;
  include wasi:random/imports@0.2.0;
  include wasi:io/imports@0.2.0;

  import wasi:filesystem/types@0.2.0;
  import wasi:filesystem/preopens@0.2.0;

  export run: func(command: string) -> string;
}
