export enum ERoutePath {
  Home = `/`,
  Teams = `/teams`,
  Team = `/teams/:teamId`,
  Secrets = `/secrets`,
  Settings = `/settings`,
  Profile = `/profile`,
  Providers = `/providers`,
  Auth = `/auth`,
  Login = `/auth/:pathname`,
  Account = `/account/:pathname`,
  Repos = `/repos`,
  Repo = `/repos/:repoId`,
  Endpoints = `/applications/:appId/endpoints`,
  Endpoint = `/applications/:appId/endpoints/:endpointId`,
  ApiTokens = `/api-tokens`,
  AI = `/ai`,
  AIAgents = `/ai/agents`,
  MCPTools = `/ai/mcp-tools`,
  Star = `*`,
}
