import {
  resetUser,
  resetOrgs,
  resetAssets,
  resetAgents,
  resetSkills,
  resetCollections,
  resetApiKeys,
  resetSkillProposals,
  resetActiveSkillProposalId,
  resetThreads,
  resetSecrets,
  resetDomains,
  resetInvoices,
  resetOrgUsers,
  resetProjects,
  resetMessages,
  resetOrgQuota,
  resetSchedules,
  resetEndpoints,
  resetFunctions,
  resetOrgLimits,
  resetProviders,
  resetThemeType,
  resetSandboxes,
  resetWaitlisted,
  resetSidebarOpen,
  resetActiveOrgId,
  resetSubscription,
  resetPaymentPlans,
  resetActiveAssetId,
  resetActiveAgentId,
  resetActiveSkillId,
  resetFaasFormState,
  resetActiveThreadId,
  resetActiveSecretId,
  resetActiveDomainId,
  resetAgentFormState,
  resetProjectMembers,
  resetProxyFormState,
  resetOnboardingState,
  resetActiveMessageId,
  resetActiveProjectId,
  resetActiveScheduleId,
  resetActiveFunctionId,
  resetActiveEndpointId,
  resetActiveOrgSecretId,
  resetActiveRailSection,
} from '@TAF/state/accessors'

export const reset = () => {
  resetWaitlisted?.()
  resetUser?.()
  resetOrgs?.()
  resetSkills?.()
  resetSkillProposals?.()
  resetActiveSkillProposalId?.()
  resetAssets?.()
  resetAgents?.()
  resetApiKeys?.()
  resetThreads?.()
  resetSecrets?.()
  resetDomains?.()
  resetInvoices?.()
  resetOrgUsers?.()
  resetProjects?.()
  resetMessages?.()
  resetOrgQuota?.()
  resetEndpoints?.()
  resetFunctions?.()
  resetOrgLimits?.()
  resetProviders?.()
  resetThemeType?.()
  resetSandboxes?.()
  resetSchedules?.()
  resetCollections?.()
  resetSidebarOpen?.()
  resetActiveOrgId?.()
  resetSubscription?.()
  resetPaymentPlans?.()
  resetActiveAssetId?.()
  resetActiveAgentId?.()
  resetActiveSkillId?.()
  resetFaasFormState?.()
  resetActiveThreadId?.()
  resetActiveSecretId?.()
  resetActiveDomainId?.()
  resetAgentFormState?.()
  resetProxyFormState?.()
  resetProjectMembers?.()
  resetOnboardingState?.()
  resetActiveMessageId?.()
  resetActiveProjectId?.()
  resetActiveScheduleId?.()
  resetActiveFunctionId?.()
  resetActiveEndpointId?.()
  resetActiveOrgSecretId?.()
  resetActiveRailSection?.()
}
