import {
  resetUser,
  resetOrgs,
  resetAssets,
  resetAgents,
  resetApiKeys,
  resetThreads,
  resetSecrets,
  resetDomains,
  resetOrgUsers,
  resetProjects,
  resetMessages,
  resetOrgQuota,
  resetEndpoints,
  resetFunctions,
  resetOrgLimits,
  resetProviders,
  resetThemeType,
  resetSidebarOpen,
  resetActiveOrgId,
  resetSubscription,
  resetPaymentPlans,
  resetActiveAssetId,
  resetActiveAgentId,
  resetFaasFormState,
  resetActiveOrgRole,
  resetActiveThreadId,
  resetOrgSecrets,
  resetActiveSecretId,
  resetActiveOrgSecretId,
  resetActiveDomainId,
  resetAgentFormState,
  resetQuickstartOpen,
  resetProxyFormState,
  resetActiveMessageId,
  resetActiveProjectId,
  resetActiveFunctionId,
  resetActiveEndpointId,
} from '@TAF/state/accessors'

export const reset = () => {
  resetUser?.()
  resetOrgs?.()
  resetAssets?.()
  resetAgents?.()
  resetApiKeys?.()
  resetThreads?.()
  resetSecrets?.()
  resetDomains?.()
  resetOrgUsers?.()
  resetProjects?.()
  resetMessages?.()
  resetOrgQuota?.()
  resetEndpoints?.()
  resetFunctions?.()
  resetOrgLimits?.()
  resetProviders?.()
  resetThemeType?.()
  resetSidebarOpen?.()
  resetActiveOrgId?.()
  resetSubscription?.()
  resetPaymentPlans?.()
  resetActiveAssetId?.()
  resetActiveAgentId?.()
  resetFaasFormState?.()
  resetActiveOrgRole?.()
  resetActiveThreadId?.()
  resetOrgSecrets?.()
  resetActiveSecretId?.()
  resetActiveOrgSecretId?.()
  resetActiveDomainId?.()
  resetAgentFormState?.()
  resetProxyFormState?.()
  resetQuickstartOpen?.()
  resetActiveMessageId?.()
  resetActiveProjectId?.()
  resetActiveFunctionId?.()
  resetActiveEndpointId?.()
}
