export const mockFileContents: Record<string, string[]> = {
  'src/agent.ts': [
    "import { Agent } from '@tdsk/agent';",
    "import { searchDocs, fetchUrl } from './tools';",
    '',
    'export const agent = new Agent({',
    "  model: 'claude-haiku-4-5',",
    "  system: 'You are a documentation researcher.',",
    '  tools: [searchDocs, fetchUrl],',
    '});',
  ],
  'src/tools.ts': [
    "import { defineTool } from '@tdsk/agent';",
    "import { z } from 'zod';",
    '',
    'export const searchDocs = defineTool({',
    "  name: 'search_docs',",
    "  description: 'Semantic search across the project vector store.',",
    '  input: z.object({',
    '    query: z.string().min(2),',
    '    limit: z.number().int().min(1).max(20).default(5),',
    '  }),',
    '  async run({ query, limit }, ctx) {',
    '    const store = ctx.env.VECTOR_STORE;',
    '    const hits = await ctx.vectors(store).search(query, { limit });',
    '    return hits.map((h) => ({ id: h.id, score: h.score }));',
    '  },',
    '});',
  ],
  'package.json': [
    '{',
    '  "name": "agent-runtime",',
    '  "version": "0.4.2",',
    '  "private": true,',
    '  "dependencies": {',
    '    "@tdsk/agent": "^0.4.0",',
    '    "zod": "^3.22.0"',
    '  }',
    '}',
  ],
  'README.md': [
    '# agent-runtime',
    '',
    'Production agent runtime.',
    '',
    '## Quick start',
    '',
    '```bash',
    'tdsk sandbox start --project agent-runtime',
    '```',
  ],
}
