#!/usr/bin/env sh


# Get all staged files filtered for Added, Copied, Modified, or Renamed changes
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$STAGED_FILES" ]; then
  echo "✅ No staged files to check."
  exit 0
fi

# Check for staged .ts, .tsx, .js, .jsx, or .json files before running biome.
if echo "$STAGED_FILES" | grep -qE '\.(js|jsx|ts|tsx|json)$'; then
  echo "🔍 Found staged TypeScript/JSON files. Running Biome..."
  pnpm precommit
  # Add any changes made by the formatters back to the staging area.
  echo "🔄 Updating git index..."
  git update-index --again
else
  echo "✅ No staged TypeScript/JSON files to lint."
fi

